CREATE DATABASE IF NOT EXISTS car;
USE car;
CREATE TABLE IF NOT EXISTS admin (uname VARCHAR(20), password VARCHAR(20));
CREATE TABLE IF NOT EXISTS car_list (id INT AUTO_INCREMENT PRIMARY KEY, car_id VARCHAR(20), name VARCHAR(20), uname  VARCHAR(20), image LONGBLOB, fuel  VARCHAR(20), fare FLOAT, booked VARCHAR(3));
CREATE TABLE IF NOT EXISTS customer (id INT AUTO_INCREMENT PRIMARY KEY, fname VARCHAR(20), lname VARCHAR(20), ph  VARCHAR(20), mail  VARCHAR(20), image LONGBLOB, uname VARCHAR(20), password VARCHAR(20));
CREATE TABLE IF NOT EXISTS image (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(20), image LONGBLOB);
CREATE TABLE IF NOT EXISTS organization (id INT AUTO_INCREMENT PRIMARY KEY, oname VARCHAR(20), ph  VARCHAR(20), mail  VARCHAR(20), image LONGBLOB, uname VARCHAR(20), password VARCHAR(20));
CREATE TABLE IF NOT EXISTS supplier (id INT AUTO_INCREMENT PRIMARY KEY, fname VARCHAR(20), lname VARCHAR(20), phone  VARCHAR(20), mail  VARCHAR(20), image LONGBLOB, uname VARCHAR(20), password VARCHAR(20));
CREATE TABLE IF NOT EXISTS transaction (id INT AUTO_INCREMENT PRIMARY KEY, uname VARCHAR(20), car_id VARCHAR(20), fromdate DATE, todate DATE);
